In [4]:
import pandas as pd

In [5]:
cars = pd.read_csv('CAR_DETAILS_FROM_CAR_DEKHO.csv')

In [6]:
cars.shape

(4340, 8)

In [7]:
cars.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [8]:
# quantos dados nulos?
cars.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [9]:
cars.describe()

              year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [10]:
cars["year"].describe()

count    4340.000000
mean     2013.090783
std         4.215344
min      1992.000000
25%      2011.000000
50%      2014.000000
75%      2016.000000
max      2020.000000
Name: year, dtype: float64

In [11]:
cars["year"].mean()

np.float64(2013.0907834101383)

In [12]:
cars["selling_price"].describe()

count    4.340000e+03
mean     5.041273e+05
std      5.785487e+05
min      2.000000e+04
25%      2.087498e+05
50%      3.500000e+05
75%      6.000000e+05
max      8.900000e+06
Name: selling_price, dtype: float64

In [13]:
# Os valores estão em Rupia indiana (INR), vamos converter para Dólar americano (USD)
# 1 INR = 0.012 USD (taxa de câmbio aproximada)
cars["selling_price_usd"] = cars["selling_price"] * 0.012

In [14]:
cars.drop(columns=["selling_price"], inplace=True)

In [15]:
cars.head()

,name,year,km_driven,fuel,seller_type,transmission,owner,selling_price_usd
0,Maruti 800 AC,2007,70000,Petrol,Individual,Manual,First Owner,720.0
1,Maruti Wagon R LXI Minor,2007,50000,Petrol,Individual,Manual,First Owner,1620.0
2,Hyundai Verna 1.6 SX,2012,100000,Diesel,Individual,Manual,First Owner,7200.0
3,Datsun RediGO T Option,2017,46000,Petrol,Individual,Manual,First Owner,3000.0
4,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner,5400.0

In [16]:
# Agora vamos organizar as colunas para ficar mais fácil de trabalhar
cars = cars[["name", "year","selling_price_usd", "km_driven", "fuel", "seller_type", "transmission", "owner"]]

In [17]:
cars.head()

,name,year,selling_price_usd,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,720.0,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,1620.0,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,7200.0,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,3000.0,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,5400.0,141000,Diesel,Individual,Manual,Second Owner

In [57]:
cars.selling_price_usd.describe()

count      4340.000000
mean       6049.527741
std        6942.584834
min         240.000000
25%        2504.997000
50%        4200.000000
75%        7200.000000
max      106800.000000
Name: selling_price_usd, dtype: float64

In [58]:
cars.km_driven.describe()

count      4340.000000
mean      66215.777419
std       46644.102194
min           1.000000
25%       35000.000000
50%       60000.000000
75%       90000.000000
max      806599.000000
Name: km_driven, dtype: float64

# 1.Qual a marca de Carros mais comercializada?

In [20]:
cars['name'].nunique()

1491

In [22]:
cars['name'].value_counts()

name
Maruti Swift Dzire VDI                      69
Maruti Alto 800 LXI                         59
Maruti Alto LXi                             47
Maruti Alto LX                              35
Hyundai EON Era Plus                        35
                                            ..
Honda Jazz Select Edition                    1
Maruti Swift Dzire AMT VXI                   1
Hyundai Creta 1.6 SX Automatic               1
Mercedes-Benz E-Class 280 CDI Elegance       1
Audi RS7 2015-2019 Sportback Performance     1
Name: count, Length: 1491, dtype: int64

In [24]:
cars[cars['name'].str.contains("Maruti")]

,name,year,selling_price_usd,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,720.0,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,1620.0,50000,Petrol,Individual,Manual,First Owner
5,Maruti Alto LX BSIII,2007,1680.0,125000,Petrol,Individual,Manual,First Owner
9,Maruti Celerio Green VXI,2017,4380.0,78000,CNG,Individual,Manual,First Owner
13,Maruti 800 AC,2007,720.0,70000,Petrol,Individual,Manual,First Owner
...,...,...,...,...,...,...,...,...
4323,Maruti 800 AC,2014,2340.0,75000,Petrol,Individual,Manual,Second Owner
4324,Maruti Alto 800 Base,2015,1860.0,40000,Petrol,Individual,Manual,First Owner
4325,Maruti Alto LXi,2000,780.0,90000,Petrol,Individual,Manual,Second Owner
4333,Maruti Ritz VDi,2012,2700.0,90000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,1320.0,83000,Petrol,Individual,Manual,Second Owner

In [33]:
# Então a Marca mais vendida é a Maruti Suzuki com 1280 carros vendidos.
quantidade = (cars['name'].str.contains('Maruti')).sum()
print(quantidade)

1280

# 2.Qual o Modelo, Ano e Valor do carro mais caro vendido?

In [44]:
cars.loc[cars.groupby('year')['selling_price_usd'].idxmax()][['name', 'year', 'selling_price_usd']].sort_values('selling_price_usd', ascending=False).head(1)

                                          name  year  selling_price_usd
3872  Audi RS7 2015-2019 Sportback Performance  2016           106800.0

# 3. Qual é o modelo de carro mais caro vendido em cada ano?

In [41]:
cars.loc[cars.groupby('year')['selling_price_usd'].idxmax()][['name', 'year', 'selling_price_usd']]

,name,year,selling_price_usd
3334,Maruti 800 AC BSII,1992,600.000
631,Maruti Gypsy E MG410W ST,1995,1140.000
61,Mahindra Jeep CL 500 MDI,1996,3000.000
1669,Mahindra Jeep CL 500 MDI,1997,1800.000
2044,Mercedes-Benz E-Class 230,1998,12000.000
1579,Mahindra Jeep Classic,1999,2040.000
1184,Maruti Gypsy King Hard Top,2000,1980.000
3916,Maruti Gypsy King HT BSIV,2001,4919.988
2641,Mahindra Jeep MM 550 XDB,2002,1800.000
1040,Honda City VTEC,2003,3720.000
2623,Ford Endeavour 2.5L 4X2 MT,2004,4800.000
1672,Ford Endeavour 4x4 XLT,2005,4200.000
2293,BMW 7 Series 730Ld,2006,12600.000
3612,Mercedes-Benz E-Class 280 CDI,2007,10800.000
3871,Mercedes-Benz E-Class 280 CDI Elegance,2008,9540.000
44,Audi Q7 35 TDI Quattro Premium,2009,15000.000
3875,Land Rover Range Rover 4.4 Diesel LWB Vogue SE,2010,50400.000
2499,BMW 7 Series 730Ld,2011,20400.000
105,BMW 7 Series 730Ld,2012,30000.000
96,Audi A8 4.2 TDI,2013,33600.000
539,Mercedes-Benz GL-Class 350 CDI Blue Efficiency,2014,52800.000
1705,Audi Q5 2.0 TDI,2015,42000.000
3872,Audi RS7 2015-2019 Sportback Performance,2016,106800.000
89,Mercedes-Benz S-Class S 350d Connoisseurs Edition,2017,97800.000
3453,BMW 5 Series 520d Luxury Line,2018,57600.000
555,BMW X5 xDrive 30d xLine,2019,59400.000
963,Audi A5 Sportback,2020,56400.000

# 4. Qual modelo de carro teve a maior media de quilometragem (km_driven) entre os carros vendidos?

In [42]:
cars.groupby('name')['km_driven'].mean().sort_values(ascending=False).head(1)

name
Maruti SX4 S Cross DDiS 320 Delta    400000.0
Name: km_driven, dtype: float64

# 5. Qual o preço médio do modelo de carro mais comercializado?

In [54]:
cars['name'].value_counts()

name
Maruti Swift Dzire VDI                      69
Maruti Alto 800 LXI                         59
Maruti Alto LXi                             47
Maruti Alto LX                              35
Hyundai EON Era Plus                        35
                                            ..
Honda Jazz Select Edition                    1
Maruti Swift Dzire AMT VXI                   1
Hyundai Creta 1.6 SX Automatic               1
Mercedes-Benz E-Class 280 CDI Elegance       1
Audi RS7 2015-2019 Sportback Performance     1
Name: count, Length: 1491, dtype: int64

In [56]:
#Qual o preço médio do modelo de carro mais comercializado?
modelo_mais_comercializado = cars['name'].value_counts().idxmax()
preco_medio = cars[cars['name'] == modelo_mais_comercializado]['selling_price_usd'].mean()
print(f"O modelo mais comercializado é {modelo_mais_comercializado} com um preço médio de {preco_medio:.2f} USD.")

O modelo mais comercializado é Maruti Swift Dzire VDI com um preço médio de 6137.56 USD.

# Maruti Swift Dzire VDI

<img src="swift-dzire.avif" alt="Maruti Swift Dzire VDI">