In [ ]:
import pandas as pd

In [11]:
cars = pd.read_csv('CAR_DETAILS_FROM_CAR_DEKHO.csv')

In [13]:
cars.shape

(4340, 8)

In [14]:
cars.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [15]:
# quantos dados nulos?
cars.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [16]:
cars.describe()

              year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [17]:
cars["year"].describe()

count    4340.000000
mean     2013.090783
std         4.215344
min      1992.000000
25%      2011.000000
50%      2014.000000
75%      2016.000000
max      2020.000000
Name: year, dtype: float64

In [18]:
cars["year"].mean()

np.float64(2013.0907834101383)

In [19]:
cars["selling_price"].describe()

count    4.340000e+03
mean     5.041273e+05
std      5.785487e+05
min      2.000000e+04
25%      2.087498e+05
50%      3.500000e+05
75%      6.000000e+05
max      8.900000e+06
Name: selling_price, dtype: float64

In [ ]:
# Os valores estão em Rupia indiana (INR), vamos converter para Dólar americano (USD)
# 1 INR = 0.012 USD (taxa de câmbio aproximada)
cars["selling_price_usd"] = cars["selling_price"] * 0.012

In [25]:
cars.drop(columns=["selling_price"], inplace=True)

In [26]:
cars.head()

,name,year,km_driven,fuel,seller_type,transmission,owner,selling_price_usd
0,Maruti 800 AC,2007,70000,Petrol,Individual,Manual,First Owner,720.0
1,Maruti Wagon R LXI Minor,2007,50000,Petrol,Individual,Manual,First Owner,1620.0
2,Hyundai Verna 1.6 SX,2012,100000,Diesel,Individual,Manual,First Owner,7200.0
3,Datsun RediGO T Option,2017,46000,Petrol,Individual,Manual,First Owner,3000.0
4,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner,5400.0

In [ ]:
# Agora vamos organizar as colunas para ficar mais fácil de trabalhar
cars = cars[["name", "year","selling_price_usd", "km_driven", "fuel", "seller_type", "transmission", "owner"]]

In [28]:
cars.head()

,name,year,selling_price_usd,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,720.0,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,1620.0,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,7200.0,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,3000.0,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,5400.0,141000,Diesel,Individual,Manual,Second Owner